# Generated by Django 5.0.4 on 2024-05-06 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaga',
            old_name='vaga',
            new_name='empresa',
        ),
    ]
