# Generated by Django 5.0.4 on 2024-05-13 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_rename_vaga_vaga_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(max_length=255, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
