# Generated by Django 5.0.4 on 2024-05-13 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_vaga_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='inativa',
            field=models.BooleanField(default=False),
        ),
    ]
