# Generated by Django 5.0.4 on 2024-05-13 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_vaga_inativa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='empresa',
            field=models.CharField(max_length=255),
        ),
    ]
