# Generated by Django 5.0.4 on 2024-05-14 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_alter_perfil_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
