# Generated by Django 5.0.4 on 2024-05-13 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_profile_delete_perfil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
